# Generated by Django 2.1.2 on 2018-11-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrating',
            name='e_rating',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='f_rating',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=2),
        ),
    ]
