# Generated by Django 2.1.1 on 2018-12-08 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0002_auto_20181122_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default=None, max_length=11),
        ),
    ]
